/* Original animated service and industry illustrations. All elements are HTML/CSS/SVG; no external imagery. */
(()=>{
const bar=(n)=>Array.from({length:n},(_,i)=>`<i style="--i:${i}"></i>`).join('');
const dot=(n)=>Array.from({length:n},(_,i)=>`<i style="--i:${i}"></i>`).join('');
const scenes={
'managed-it':{tag:'01 / MANAGED IT',foot:'Monitoring · Support · Recovery',body:`<div class="scene-monitor"><div class="scene-monitor-top"><span>FLEET OVERVIEW</span><span class="online-mark">● ALL SIGNALS VISIBLE</span></div><div class="monitor-chart">${bar(16)}</div><div class="monitor-rows"><div><span>01</span> ENDPOINT HEALTH <b class="monitor-status">● ACTIVE</b></div><div><span>02</span> BACKUP CHECK <b class="monitor-status">● REVIEWED</b></div><div><span>03</span> SUPPORT QUEUE <b class="monitor-status">● TRACKED</b></div></div></div><div class="scene-orb scene-orb-a"></div>`},
'infrastructure':{tag:'02 / INFRASTRUCTURE',foot:'Rack · Power · Deploy',body:`<div class="rack-floor"></div><div class="rack-grid"><div class="rack rack-one"><span>01 / CORE</span>${bar(5)}</div><div class="rack rack-two"><span>02 / COMPUTE</span>${bar(6)}</div><div class="rack rack-three"><span>03 / BACKUP</span>${bar(4)}</div></div><div class="rack-cable"><i></i></div><div class="rack-label">DEPLOYMENT PATH <b>→</b> VERIFIED</div>`},
'network-solutions':{tag:'03 / NETWORKS',foot:'Route · Observe · Connect',body:`<div class="mesh"><svg viewBox="0 0 480 310" preserveAspectRatio="none" aria-hidden="true"><path d="M76 153 L196 73 L328 110 L418 51 M76 153 L195 241 L328 110 L418 238 M195 241 L418 238"/><circle class="mesh-packet" r="5"><animateMotion dur="3.1s" repeatCount="indefinite" path="M76 153 L196 73 L328 110 L418 51"/></circle><circle class="mesh-packet alt" r="5"><animateMotion dur="3.8s" repeatCount="indefinite" path="M76 153 L195 241 L328 110 L418 238"/></circle></svg><span class="mesh-node m1">A</span><span class="mesh-node m2">B</span><span class="mesh-node m3">C</span><span class="mesh-node m4">D</span><span class="mesh-node m5">E</span><span class="mesh-node m6">F</span></div><div class="mesh-caption">ROUTE OPTIMISED <span>●</span> PATH VISIBLE</div>`},
'cybersecurity':{tag:'04 / CYBERSECURITY',foot:'Identify · Protect · Respond',body:`<div class="shield-rings"><i></i><i></i><i></i></div><div class="shield-unit"><svg viewBox="0 0 200 235" aria-hidden="true"><path d="M100 11 178 45v75c0 56-28 86-78 105-50-19-78-49-78-105V45z" fill="#144b8b" stroke="#78e8ff" stroke-width="5"/><path d="m61 121 26 27 54-58" fill="none" stroke="#b6faff" stroke-width="11" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="shield-scan"></div></div><span class="security-chip one">ACCESS CHECK</span><span class="security-chip two">RECOVERY PLAN</span>`},
'cloud-solutions':{tag:'05 / CLOUD PLATFORMS',foot:'Discover · Move · Operate',body:`<div class="cloud-halo"></div><div class="cloud-shape"><span></span><span></span><span></span><b>CLOUD</b></div><div class="sync-path"><span class="sync-dot d1"></span><span class="sync-dot d2"></span></div><div class="cloud-device left">WORKLOAD <b>01</b></div><div class="cloud-device right">ACCESS <b>02</b></div><div class="cloud-foot">↥ &nbsp; MIGRATION FLOW &nbsp; ↧</div>`},
'business-communications':{tag:'06 / COMMUNICATIONS',foot:'Call · Meet · Collaborate',body:`<div class="comms-avatar left">A<span>TEAM</span></div><div class="comms-avatar right">B<span>TEAM</span></div><div class="comms-signal"><div class="waveform">${bar(19)}</div><span>VOICE + COLLABORATION</span></div><div class="comms-path"><span class="comms-packet"></span></div><div class="comms-indicator">● CONNECTED CHANNEL</div>`},
'ai-automation':{tag:'07 / AUTOMATION',foot:'Trigger · Review · Deliver',body:`<div class="automation-lane"><div class="automation-step"><span>01</span><b>REQUEST</b></div><i class="automation-connector"><em></em></i><div class="automation-step"><span>02</span><b>VALIDATE</b></div><i class="automation-connector"><em></em></i><div class="automation-step"><span>03</span><b>APPROVE</b></div><i class="automation-connector"><em></em></i><div class="automation-step"><span>04</span><b>DONE</b></div></div><div class="automation-log"><span>↳ CHECKPOINT RECORDED</span><span>↳ HUMAN REVIEW READY</span></div>`},
'ict-procurement':{tag:'08 / TECH SOURCING',foot:'Compare · Choose · Track',body:`<div class="sourcing-line"></div><div class="sourcing-cards"><div><span>01</span><b>REQUIREMENTS</b><i>✓</i></div><div><span>02</span><b>OPTIONS</b><i>✓</i></div><div><span>03</span><b>ROLL OUT</b><i>✓</i></div></div><div class="sourcing-stamp">LIFECYCLE IN VIEW <span>↗</span></div>`},
'retail':{tag:'RETAIL / STORE OPERATIONS',foot:'Checkout · Devices · Support',body:`<div class="retail-terminal"><div class="terminal-screen"><span>STORE 01 / READY</span><div class="terminal-product">◇ <b>ITEM SCANNED</b><i></i></div><div class="terminal-product">◇ <b>STOCK UPDATED</b><i></i></div><div class="terminal-total">TRANSACTION FLOW <b>→</b></div></div><div class="terminal-base"></div></div><div class="retail-scan"></div>`},
'travel-hospitality':{tag:'TRAVEL / GUEST JOURNEY',foot:'Reserve · Arrive · Connect',body:`<div class="journey-card"><span>GUEST JOURNEY <b>ACTIVE</b></span><div class="journey-route"><i class="j1">1</i><em></em><i class="j2">2</i><em></em><i class="j3">3</i></div><div class="journey-label"><span>BOOKING</span><span>ARRIVAL</span><span>SUPPORT</span></div><div class="journey-progress"><i></i></div></div><div class="journey-orbit"></div>`},
'professional-services':{tag:'PROFESSIONAL / WORKFLOW',foot:'Share · Review · Deliver',body:`<div class="document-stack"><div class="document back"><span>CLIENT FILE</span></div><div class="document mid"><span>REVIEW / 02</span></div><div class="document front"><span>PROJECT BRIEF</span><i></i><i></i><i></i><b>✓ APPROVED</b></div></div><div class="document-cursor">↗</div>`},
'construction':{tag:'CONSTRUCTION / FIELD TO OFFICE',foot:'Plan · Build · Update',body:`<div class="blueprint"><div class="blueprint-grid"></div><div class="build-outline"><span></span><span></span><span></span><span></span></div><div class="build-crane"><i></i><b></b></div><div class="build-pin">SITE 01 <em>● LIVE UPDATE</em></div></div>`},
'healthcare':{tag:'HEALTHCARE / CONTINUITY',foot:'Access · Protect · Recover',body:`<div class="care-card"><span>CARE SYSTEMS <b>● AVAILABLE</b></span><svg viewBox="0 0 430 130" preserveAspectRatio="none"><path d="M0 69 H75 L95 69 118 35 145 110 168 51 185 69 H250 L267 69 288 40 313 102 332 69 H430"/></svg><div class="care-meta"><span>ACCESS</span><span>DEVICE</span><span>BACKUP</span></div></div><div class="care-pulse"></div>`},
'property-real-estate':{tag:'PROPERTY / CONNECTED PLACES',foot:'Sites · Agents · Systems',body:`<div class="property-city"><div class="building small">${bar(6)}</div><div class="building tall">${bar(12)}</div><div class="building mid">${bar(9)}</div><div class="building short">${bar(4)}</div><div class="property-ground"></div></div><div class="property-pins"><span>01</span><span>02</span><span>03</span></div><div class="property-route"></div>`}
};
const render=(target,key)=>{const data=scenes[key];if(!target||!data)return;target.innerHTML=`<div class="service-scene scene-${key}"><div class="scene-topline"><span class="scene-led"></span>${data.tag}<span class="scene-spark">✦</span></div><div class="scene-body">${data.body}</div><div class="scene-bottomline"><span>${data.foot}</span><span>IT CLOUD HUB ↗</span></div></div>`;target.dataset.scene=key;if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)target.querySelectorAll?.('svg').forEach(svg=>svg.pauseAnimations?.())};
window.ITScenes={render,keys:Object.keys(scenes)};
document.querySelectorAll('.scene-detail').forEach(el=>render(el,el.dataset.scene));
})();
