(()=>{
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.primary-nav');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=760){nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}}));
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('visible'));
const counters=document.querySelectorAll('[data-count]');if(counters.length){const run=el=>{const target=Number(el.dataset.count);if(matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=target;return}const t=performance.now(),duration=950;function tick(now){const progress=Math.min(1,(now-t)/duration);el.textContent=Math.round(target*(1-(1-progress)**3));if(progress<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)};if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){run(e.target);io.unobserve(e.target)}}));counters.forEach(el=>io.observe(el))}else counters.forEach(run)}
const slides=[...document.querySelectorAll('.slide-copy')],dots=[...document.querySelectorAll('.slide-control')],toggle=document.querySelector('.slider-toggle'),visualLabel=document.querySelector('#visualLabel');let current=0,paused=false,timer;
const sceneKeys=['managed-it','infrastructure','network-solutions','cybersecurity','cloud-solutions','business-communications','ai-automation','ict-procurement'];const sceneStage=document.querySelector('.scene-stage'),heroVisual=document.querySelector('.hero-visual');
const activate=index=>{if(!slides.length)return;current=index;window.ITScenes?.render(sceneStage,sceneKeys[index]);if(heroVisual)heroVisual.dataset.scene=sceneKeys[index];slides.forEach((el,i)=>{const active=i===index;el.classList.toggle('active',active);el.setAttribute('aria-hidden',String(!active));el.querySelectorAll('a').forEach(a=>a.tabIndex=active?0:-1)});dots.forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-current',String(i===index));el.classList.remove('paused')});if(visualLabel)visualLabel.textContent=['MANAGED IT','INFRASTRUCTURE','NETWORKS','CYBERSECURITY','CLOUD PLATFORMS','COMMUNICATIONS','AUTOMATION','TECH SOURCING'][index];clearTimeout(timer);if(!paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches)timer=setTimeout(()=>activate((current+1)%slides.length),7000)};
dots.forEach(d=>d.addEventListener('click',()=>activate(Number(d.dataset.go))));toggle?.addEventListener('click',()=>{paused=!paused;toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Play slides':'Pause slides');toggle.textContent=paused?'▶':'Ⅱ';if(paused){clearTimeout(timer);dots[current]?.classList.add('paused')}else activate(current)});if(slides.length)activate(0);
const tabs=[...document.querySelectorAll('.scenario-tab')],heading=document.querySelector('#scenario-title'),description=document.querySelector('#scenario-description'),link=document.querySelector('#scenario-link');const scenarios=[['Infrastructure','Map access, devices and connectivity before the first team arrives.','infrastructure'],['Managed IT','Find repeating incidents and turn them into a maintenance plan.','managed-it'],['Automation','Trace where work waits, then design a workflow with clear checks.','ai-automation']];tabs.forEach(tab=>tab.addEventListener('click',()=>{const i=Number(tab.dataset.scenario),item=scenarios[i];tabs.forEach(t=>{const selected=t===tab;t.classList.toggle('active',selected);t.setAttribute('aria-selected',String(selected))});heading.textContent=item[0];description.textContent=item[1];link.href=`./services/${item[2]}/`}));
const form=document.querySelector('#brief-form');form?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(form),brief=`IT Cloud Hub project brief\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nTopic: ${d.get('topic')}\n\n${d.get('message')}`,note=form.querySelector('.form-note');try{await navigator.clipboard.writeText(brief);note.textContent='Brief copied. Paste it into your email or preferred contact channel.'}catch{const box=document.createElement('textarea');box.value=brief;box.readOnly=true;box.setAttribute('aria-label','Project brief to copy');form.append(box);box.select();note.textContent='Select and copy the brief shown below.'}});
})();
